server:
  port: 8090
spring:
  data:
    mongodb:
      uri: mongodb://customer_api:customer_pwd@localhost:27017/customer?authSource=customer
    logging:
      level:
        org.mongodb.driver: DEBUG
